import { useEffect, useMemo, useState } from 'react'; import { useNavigate, useParams } from 'react-router-dom'; import { ArrowLeft, Check, Clock3, Coins, Lightbulb, Star, X } from 'lucide-react'; import { supabase } from '../lib/supabase'

type Q={id:number;prompt:string;options:string[];difficulty:number;xp:number;source_title:string|null;source_page:number|null;skill?:{name_ar:string}|null}
export default function Mission(){
  const nav=useNavigate(); const {code}=useParams(); const [mission,setMission]=useState<any>(null); const [questions,setQuestions]=useState<Q[]>([]); const [idx,setIdx]=useState(0); const [selected,setSelected]=useState<number|null>(null); const [result,setResult]=useState<any>(null); const [score,setScore]=useState(0); const [done,setDone]=useState(false); const [loading,setLoading]=useState(true); const started=useMemo(()=>Date.now(),[idx])
  useEffect(()=>{(async()=>{if(!supabase||!code)return; const {data:m,error}=await supabase.from('missions').select('id,code,title_ar,subtitle_ar,reward_xp,reward_coins').eq('code',code).single(); if(error||!m){setLoading(false);return} setMission(m); const {data:mq}=await supabase.from('mission_questions').select('sort_order,question:questions(id,prompt,options,difficulty,xp,source_title,source_page,skill:skills(name_ar))').eq('mission_id',m.id).order('sort_order'); setQuestions((mq||[]).map((x:any)=>x.question).filter(Boolean)); setLoading(false)})()},[code])
  const q=questions[idx]
  async function choose(i:number){if(selected!==null||!supabase||!q||!mission)return;setSelected(i);const responseMs=Date.now()-started;const {data,error}=await supabase.rpc('submit_answer',{p_question_id:q.id,p_mission_id:mission.id,p_selected_index:i,p_response_ms:responseMs});if(error){setResult({is_correct:false,explanation:'تعذر حفظ الإجابة. حاول مرة أخرى.',correct_index:-1,xp_earned:0});return}setResult(data);if(data?.is_correct)setScore(s=>s+1)}
  function next(){if(idx===questions.length-1){setDone(true);return}setIdx(i=>i+1);setSelected(null);setResult(null)}
  if(loading)return <main className="page centered"><div className="glass loading-card">جارٍ تحميل المهمة...</div></main>
  if(!mission||!q)return <main className="page centered"><div className="glass loading-card">لا توجد أسئلة متاحة لهذه المهمة بعد.<br/><button className="primary" onClick={()=>nav('/map')}>العودة للخريطة</button></div></main>
  if(done){const pct=Math.round((score/questions.length)*100);return <main className="page centered victory"><section className="victory-card glass"><div className="crown-big">🏆</div><span className="eyebrow">اكتملت المهمة</span><h1>{mission.title_ar}</h1><p>أجبت إجابة صحيحة عن {score} من {questions.length} — الدقة {pct}%</p><div className="reward-row"><span><Star/> نقاط الإجابات محفوظة</span><span><Coins/> المكافآت تتطور مع تقدمك</span></div><button className="primary" onClick={()=>nav('/map')}>متابعة الرحلة <ArrowLeft/></button></section></main>}
  const isCorrect=result?.is_correct===true
  return <main className="page mission-page"><div className="mission-head"><button className="icon-btn" onClick={()=>nav('/map')}><X/></button><div><span>{mission.title_ar}</span><b>السؤال {idx+1} من {questions.length}</b></div><span className="timer"><Clock3/> +{q.xp} XP</span></div><div className="progress-track"><i style={{width:`${((idx+(selected!==null?1:0))/questions.length)*100}%`}}/></div><section className="question-wrap"><div className="question-meta"><span>{q.skill?.name_ar||'قدرات لفظية'}</span><span>الصعوبة {'★'.repeat(q.difficulty)}</span></div><h1>{q.prompt}</h1><div className="options">{q.options.map((o,i)=>{let c='';if(result){if(i===result.correct_index)c='correct';else if(i===selected)c='wrong'}return <button key={i} onClick={()=>choose(i)} className={c} disabled={selected!==null}><span>{['أ','ب','ج','د','هـ','و'][i]}</span>{o}{c==='correct'&&<Check/>}{c==='wrong'&&<X/>}</button>})}</div>{result&&<div className={`feedback ${isCorrect?'good':'bad'}`}><b>{isCorrect?'إجابة صحيحة':'ليست الإجابة الصحيحة'}</b><p>{result.explanation}</p><small>المصدر: {q.source_title||'مذكرات المشكاة'}{q.source_page?` • ص ${q.source_page}`:''}</small></div>}<div className="mission-actions"><button className="hint" disabled><Lightbulb/> تلميح</button><button className="primary" disabled={!result} onClick={next}>{idx===questions.length-1?'إنهاء المهمة':'السؤال التالي'} <ArrowLeft/></button></div></section></main>
}
